# Generated by Django 4.1.6 on 2023-07-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapinapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(default='', max_length=14),
        ),
    ]
