# Generated by Django 4.1.6 on 2023-07-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapinapp', '0002_alter_contact_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=120)),
                ('useremail', models.CharField(default='', max_length=120)),
                ('usermobile', models.CharField(default='', max_length=120)),
                ('usercity', models.CharField(default='', max_length=120)),
                ('userdob', models.CharField(default='', max_length=120)),
                ('usergender', models.CharField(default='', max_length=120)),
                ('guardiansname', models.CharField(default='', max_length=120)),
                ('guardiansphone', models.CharField(default='', max_length=120)),
                ('userschool', models.CharField(default='', max_length=120)),
                ('userclass', models.CharField(default='', max_length=120)),
            ],
        ),
    ]
