# Generated by Django 4.1.6 on 2023-07-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapinapp', '0003_newuserdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuserdata',
            name='userpassword',
            field=models.CharField(default='', max_length=30),
        ),
    ]
