# Generated by Django 4.1.6 on 2023-07-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapinapp', '0005_newuserdata_userbatch_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuserdata',
            name='batch_purchased',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='newuserdata',
            name='userbatch',
            field=models.CharField(default='', max_length=80),
        ),
    ]
