# Generated by Django 4.1.6 on 2023-07-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapinapp', '0006_newuserdata_batch_purchased_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuserdata',
            name='userbatch',
            field=models.CharField(default='', max_length=200),
        ),
    ]
