# Generated by Django 4.1.6 on 2023-07-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octapinapp', '0007_alter_newuserdata_userbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobilenum', models.CharField(default='', max_length=12)),
                ('adminname', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='BatchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BatchName', models.CharField(default='', max_length=100)),
                ('Batchfees', models.CharField(default='', max_length=12)),
                ('BatchDfees', models.CharField(default='', max_length=12)),
                ('duration', models.CharField(default='', max_length=12)),
                ('startdate', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
